### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by yz21606948** [josiahcarlson/rpqueue#19]
Thanks

**Comment by josiahcarlson** [comment]
Please don't create an issue when you have a question. You can find my email attached to my github user, and you can email me directly with `rpqueue` in the subject.

But to run tests, you do `make test` after cloning the repository. The tests are run for Python 2.6, 2.7, 3.3, 3.4, 3.5, and 3.6. You can look into the `Makefile` to see how I run tests, if you don't have all versions of Python available.
