### ISSUE TITLE
@task decorator is not working 

### ISSUE THREAD

**Issue by makov44** [josiahcarlson/rpqueue#24]
This change introduces a new bug:
https://github.com/josiahcarlson/rpqueue/commit/6d9caa76dd98e3a08975f401bdc178c4b951b41a#diff-2cee58761fd6da04a3218ebb31016238
To reproduce use @task decorator without parameters:

```
@rpqueue.task
def task1(a):
    saw[0] = a
```

You will get error:

```
 File "/opt/chownow/venv-hermosa/local/lib/python2.7/site-packages/rpqueue/__init__.py", line 1364, in execute_tasks
   __import__(module) # for any connection modification side-effects
 File "/opt/chownow/Hermosa/_tasks.py", line 7, in <module>
   import tasks
 File "/opt/chownow/Hermosa/tasks/__init__.py", line 7, in <module>
   from . import billing
 File "/opt/chownow/Hermosa/tasks/billing.py", line 10, in <module>
   @close_session
 File "/opt/chownow/venv-hermosa/local/lib/python2.7/site-packages/rpqueue/__init__.py", line 1233, in task
   return decorate(args[0])
TypeError: 'function' object has no attribute '__getitem__'
```
*args is a list of parametrs and args is just one parameter
This code will throw exception: return decorate(args[0])

**Comment by josiahcarlson** [comment]
I'm working on this now.

**Comment by josiahcarlson** [comment]
Which version of the Redis client are you using?

**Comment by makov44** [comment]
I was using redis==2.10.6

**Comment by makov44** [comment]
Can you also reconsider using method `itertools.izip(*iterators)` ?  Looks like python3 don't support that method.

**Comment by josiahcarlson** [comment]
Yeah. I'm fixing all of this at once. Ask your COO Eric Jaffe for my phone number and give me a call, so I can make sure to get this fixed for you all.

**Comment by josiahcarlson** [comment]
Let me know if 0.30.2 fixes it for you.

**Comment by makov44** [comment]
Thank you for a fast fix.  We are thinking to use version v0.27.1 with minor changes since we are not using Lua. Can we rely on your help if we have any ussies with v0.27.1 on python2/3 environment?

**Comment by josiahcarlson** [comment]
I can maintain the 0.27.* for you guys, just let me know what is broken / needs changes, and if you want me to create a separate 0.27 branch here for to work against.

**Comment by makov44** [comment]
I will create a new pull request for branch 0.27.1. Let me know if my changes make sense for you.
It is just cosmetic changes proposed by futurize module.
Separate 0.27 branch will be preferable.

**Comment by josiahcarlson** [comment]
@makov44 I know this is 3 years past, and things should have been working, but have you moved on from the 0.27+ branch? Are you all using a recent enough Python that I can close this issue?

**Comment by makov44** [comment]
@josiahcarlson Yes, you can close this issue
