### ISSUE TITLE
save_results documentation

### ISSUE THREAD

**Issue by posix4e** [josiahcarlson/rpqueue#25]
Where is the documentation around the integer passed to save_results, maybe
https://github.com/josiahcarlson/rpqueue/blame/master/README.rst#L161

**Comment by posix4e** [comment]
Nevermind I found it

**Comment by josiahcarlson** [comment]
For others, it's documented here: https://josiahcarlson.github.io/rpqueue/README.html#automatically-storing-results-of-tasks
